name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    outputs:
      docker-tag: ${{ steps.docker-meta.outputs.tags }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker meta
      id: docker-meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/davidjameshowell/privatebin
        tags: |
          type=sha

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.docker-meta.outputs.tags }}
        labels: ${{ steps.docker-meta.outputs.labels }}

  # deploy:
  #   runs-on: self-hosted
  #   needs: build_and_push

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3

  #   - name: Install and configure kubectl
  #     run: |
  #       VERSION=$(curl --silent https://storage.googleapis.com/kubernetes-release/release/stable.txt)
  #       curl https://storage.googleapis.com/kubernetes-release/release/$VERSION/bin/linux/amd64/kubectl \
  #         --location \
  #         --remote-name \
  #         --progress-bar
  #       chmod +x kubectl
  #       sudo mv kubectl /usr/local/bin/

  #   - name: Update File
  #     run: |
  #       echo ${{ needs.build_and_push.outputs.docker-tag }}
  #       sed -i "s#ghcr.io/davidjameshowell/privatebin:latest#${{ needs.build_and_push.outputs.docker-tag }}#g" k8-statefulset.yaml

  #   - name: Deploy to Kubernetes
  #     run: |
  #       kubectl apply -f k8-statefulset.yaml